export const workingPhrases = [
	"Codemaxxxing",
	"Vibemaxxxing",
	"Bugmaxxxing",
	"Testmaxxxing",
	"Tokenmaxxxing",
	"Proving P = NP",
	"Computing 6 x 9",
	"Computing 6 x 7",
	"Mining crypto",
	"Dividing by 0",
	"Initializing killbot",
	"Downloading RAM",
	"Hacking the mainframe",
	"Rebooting the matrix",
	"Ordering 1s and 0s",
	"Navigating neural network",
	"Importing machine learning",
	"Creating unresolved tension",
	"Symlinking emacs and vim to ed",
	"Training branch predictor",
	"Timing cache hits",
	"Hacking",
	"Hacking the net",
	"Consulting a higher power",
	"Consulting the dark lord",
	"Consulting sacred texts",
	"Finding deeper understanding",
	"Opening dark portal",
	"Performing arcane ritual",
	"Uncovering ancient secrets",
	"Uncovering forbidden knowledge",
	"Uncovering hidden truths",
	"Uncovering lost wisdom",
	"Uncovering forbidden lore",
	"Uncovering hidden dimensions",
	"Enscribing runes",
	"Calculating airspeed velocity",
	"Gathering entropy",
	"Hacking 127.0.0.1",
	"Breaking AES-256",
	"Recovering original plaintext from SHA-512 hashes",
	"Spicing up passwords with salt and pepper",
	"Peeling onion routes",
	"Wrapping packets",
	"Resurrecting dead code",
	"Using default credentials",
	"Treating all user input as benign",
	"Fixing the world's problems with blockchain",
	"Installing Gentoo",
	"Installing Arch Linux",
	"Installing from source",
	"Reserving disk space for spaces instead of tabs",
	"Initializing bugs",
	"Using hard-coded secrets",
	"Granting highest privileges for simplicity",
	"Hiding keys for backdoor",
	"Stealing user data",
	"Setting up trackers",
	"Dereferencing NULL pointers",
	"Training AI with cat pictures",
	"Scanning port 65536",
	"Deleting system32",
	"Pushing secrets to public git repository",
	"Extinguishing Firewall",
	"Listening on 0.0.0.0",
	"Encrypting with SHA-256",
	"Releasing ransomware into the network",
	"Adjusting bell curves",
	"Aligning covariance matrices",
	"Applying feng shui shaders",
	"Asserting packed exemplars",
	"Attempting to lock back-buffer",
	"Binding sapling root system",
	"Building data trees",
	"Bureacritizing bureaucracies",
	"Calculating inverse probability matrices",
	"Calculating llama expectoration trajectory",
	"Cohorting exemplars",
	"Compounding inert tessellations",
	"Computing optimal bin packing",
	"Concatenating sub-contractors",
	"Containing existential buffer",
	"Debarking ark ramp",
	"Debunching unionized commercial services",
	"Deciding what message to display next",
	"Decomposing singular values",
	"Depixelating inner surface back faces",
	"Depositing slush funds",
	"Destabilizing economic indicators",
	"Determining width of blast fronts",
	"Deunionizing bulldozers",
	"Dicing models",
	"Downloading satellite terrain data",
	"Exposing flash variables to streak system",
	"Extracting resources",
	"Factoring pay scale",
	"Fixing election outcome matrix",
	"Flushing pipe network",
	"Gathering particle sources",
	"Gesticulating mimes",
	"Hiding willio webnet mask",
	"Increasing accuracy of RCI simulators",
	"Increasing magmafacation",
	"Initializing robotic click-path AI",
	"Inserting sublimated messages",
	"Integrating curves",
	"Integrating illumination form factors",
	"Integrating population graphs",
	"Iterating cellular automata",
	"Lecturing errant subsystems",
	"Modeling object components",
	"Mopping occupant leaks",
	"Normalizing power",
	"Obfuscating quigley matrix",
	"Perturbing matrices",
	"Populating lot templates",
	"Preparing sprites for random walks",
	"Realigning alternate time frames",
	"Reconfiguring user mental processes",
	"Removing texture gradients",
	"Resolving GUID conflict",
	"Reticulating splines",
	"Retracting phong shader",
	"Retrieving from back store",
	"Routing neural network infanstructure",
	"Seeding simulation parameters",
	"Sequencing particles",
	"Setting advisor moods",
	"Setting universal physical constants",
	"Sonically enhancing occupant-free timber",
	"Speculating stock market indices",
	"Splatting transforms",
	"Stratifying ground layers",
	"Synthesizing wavelets",
	"Time-compressing simulator clock",
	"Unable to reveal current activity",
	"Rolling dice",
	"Expanding the space-time continuum",
	"Engaging",
	"Electrifying the crystals",
	"Summoning dark forces",
	"Powers the banks",
	"Sorting the bits",
	"Deferring to higher powers",
	"Praying",
	"Sending thoughts and prayers",
	"Unraving the code",
	"Expanding the universe",
	"Reheating logs",
] as const;
